[package]
name = "subset"
version = "0.8.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dump-parser = { path = "../dump-parser" }
tempfile = "3.3"
md5 = "0.7"
